openapi: 3.0.3
info:
  title: All in one Jobs Api
  version: 1.0.0
  description: this api will scrape data from your favourite jobs website and serve
    it to you as an api so that you dont have to visit each website on your own while
    job hunting
paths:
  /scrapper/jobnames/:
    get:
      operationId: List JobNames
      description: ''
      parameters:
      - name: ordering
        required: false
        in: query
        description: Which field to use when ordering the results.
        schema:
          type: string
      - name: search
        required: false
        in: query
        description: A search term.
        schema:
          type: string
      tags:
      - jobnames
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/JobsCategory'
          description: ''
    post:
      operationId: 
      description: ''
      tags:
      - jobnames
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JobsCategory'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/JobsCategory'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/JobsCategory'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobsCategory'
          description: ''
  /scrapper/jobnames/{name}/:
    get:
      operationId: jobnames_retrieve
      description: ''
      parameters:
      - in: path
        name: name
        schema:
          type: string
        required: true
      tags:
      - jobnames
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobsCategory'
          description: ''
    put:
      operationId: jobnames_update
      description: ''
      parameters:
      - in: path
        name: name
        schema:
          type: string
        required: true
      tags:
      - jobnames
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JobsCategory'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/JobsCategory'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/JobsCategory'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobsCategory'
          description: ''
    patch:
      operationId: jobnames_partial_update
      description: ''
      parameters:
      - in: path
        name: name
        schema:
          type: string
        required: true
      tags:
      - jobnames
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedJobsCategory'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedJobsCategory'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedJobsCategory'
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobsCategory'
          description: ''
    delete:
      operationId: jobnames_destroy
      description: ''
      parameters:
      - in: path
        name: name
        schema:
          type: string
        required: true
      tags:
      - jobnames
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '204':
          description: No response body
  /scrapper/jobs/:
    get:
      operationId: jobs_list
      description: ''
      parameters:
      - name: ordering
        required: false
        in: query
        description: Which field to use when ordering the results.
        schema:
          type: string
      - name: page
        required: false
        in: query
        description: A page number within the paginated result set.
        schema:
          type: integer
      - name: search
        required: false
        in: query
        description: A search term.
        schema:
          type: string
      tags:
      - jobs
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedJobsList'
          description: ''
    post:
      operationId: jobs_create
      description: ''
      tags:
      - jobs
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Jobs'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Jobs'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Jobs'
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Jobs'
          description: ''
  /scrapper/jobs/{jobCategory}/:
    get:
      operationId: jobs_retrieve
      description: ''
      parameters:
      - in: path
        name: jobCategory
        schema:
          type: integer
        required: true
      tags:
      - jobs
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Jobs'
          description: ''
    put:
      operationId: jobs_update
      description: ''
      parameters:
      - in: path
        name: jobCategory
        schema:
          type: integer
        required: true
      tags:
      - jobs
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Jobs'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Jobs'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Jobs'
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Jobs'
          description: ''
    patch:
      operationId: jobs_partial_update
      description: ''
      parameters:
      - in: path
        name: jobCategory
        schema:
          type: integer
        required: true
      tags:
      - jobs
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedJobs'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedJobs'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedJobs'
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Jobs'
          description: ''
    delete:
      operationId: jobs_destroy
      description: ''
      parameters:
      - in: path
        name: jobCategory
        schema:
          type: integer
        required: true
      tags:
      - jobs
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '204':
          description: No response body
components:
  schemas:
    Jobs:
      type: object
      properties:
        title:
          type: string
          nullable: true
          maxLength: 255
        rating:
          type: string
          nullable: true
          maxLength: 255
        location:
          type: string
          nullable: true
          maxLength: 255
        company_name:
          type: string
          nullable: true
          maxLength: 255
        created_at:
          type: string
          format: date-time
          readOnly: true
        jobCategory:
          type: integer
          nullable: true
        id:
          type: integer
          readOnly: true
        link:
          type: string
          nullable: true
          maxLength: 11250
        job_by:
          type: string
          nullable: true
          maxLength: 255
      required:
      - created_at
      - id
    JobsCategory:
      type: object
      properties:
        name:
          type: string
          maxLength: 244
      required:
      - name
    PaginatedJobsList:
      type: object
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=4
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?page=2
        results:
          type: array
          items:
            $ref: '#/components/schemas/Jobs'
    PatchedJobs:
      type: object
      properties:
        title:
          type: string
          nullable: true
          maxLength: 255
        rating:
          type: string
          nullable: true
          maxLength: 255
        location:
          type: string
          nullable: true
          maxLength: 255
        company_name:
          type: string
          nullable: true
          maxLength: 255
        created_at:
          type: string
          format: date-time
          readOnly: true
        jobCategory:
          type: integer
          nullable: true
        id:
          type: integer
          readOnly: true
        link:
          type: string
          nullable: true
          maxLength: 11250
        job_by:
          type: string
          nullable: true
          maxLength: 255
    PatchedJobsCategory:
      type: object
      properties:
        name:
          type: string
          maxLength: 244
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: Session
